(() => {
  'use strict';
  const app = document.querySelector('#app');
  const KEY = 'mi-recetario-v1';
  const starters = [
    {id:'demo-pasta',name:'Pasta Alfredo',category:'Cena',minutes:30,servings:4,difficulty:'Fácil',emoji:'🍝',ingredients:['500 g de pasta','250 ml de crema de leche','100 g de queso parmesano','Sal al gusto'],steps:['Hervir la pasta hasta que esté al dente.','Calentar la crema de leche a fuego bajo.','Agregar el queso parmesano y mezclar.','Incorporar la pasta a la salsa y servir.'],favorite:false},
    {id:'demo-pollo',name:'Pollo al horno',category:'Almuerzo',minutes:45,servings:4,difficulty:'Fácil',emoji:'🍗',ingredients:['4 piezas de pollo','2 papas','2 dientes de ajo','Sal y orégano'],steps:['Precalentar el horno a 200 °C.','Sazonar el pollo y cortar las papas.','Colocar todo en una bandeja.','Hornear hasta que el pollo esté bien cocido.'],favorite:false},
    {id:'demo-bizcocho',name:'Bizcocho de vainilla',category:'Postres',minutes:60,servings:8,difficulty:'Media',emoji:'🍰',ingredients:['2 tazas de harina','3 huevos','1 taza de azúcar','1 cucharadita de vainilla'],steps:['Precalentar el horno a 180 °C.','Batir huevos y azúcar.','Agregar harina y vainilla.','Verter en un molde y hornear hasta que esté cocido.'],favorite:false}
  ];
  let data = read();
  let page = 'home', category = 'Todas', query = '', editing = null, message = '';
  function read(){try{return JSON.parse(localStorage.getItem(KEY)) || {users:{},session:null}}catch{return {users:{},session:null}}}
  function save(){localStorage.setItem(KEY,JSON.stringify(data));window.RecetarioExtras?.changed()}
  function user(){return data.session && data.users[data.session]}
  function recipes(){return user()?.recipes || []}
  function esc(v){return String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function icon(){return '<img src="icons/icon.svg" alt="">'}
  async function hash(pass,salt){const bytes=new TextEncoder().encode(salt+':'+pass);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
  function random(){const a=new Uint8Array(16);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
  function nav(){return `<nav class="nav" aria-label="Navegación principal"><button data-go="home" class="${page==='home'?'active':''}"><span>⌂</span>Inicio</button><button data-go="favorites" class="${page==='favorites'?'active':''}"><span>♡</span>Favoritos</button><button data-go="inventory"><span>▣</span>Inventario</button><button data-go="shop"><span>🛒</span>Compras</button><button data-go="profile" class="${page==='profile'?'active':''}"><span>♙</span>Perfil</button></nav>`}
  function shell(body){app.innerHTML=`<main class="shell">${body}${nav()}</main>`}
  function legacyAuth(register=false,error=''){app.innerHTML=`<main class="auth"><img class="logo" src="icons/icon.svg" alt=""><h1>Mi Recetario</h1><p class="subtitle">Tus recetas, a tu manera</p><form id="auth" class="panel"><h2>${register?'Crear cuenta':'Iniciar sesión'}</h2>${error?`<p class="error" role="alert">${esc(error)}</p>`:''}<label class="field">Usuario<input name="username" autocomplete="username" required minlength="3" maxlength="30"></label><label class="field">Contraseña<input name="password" type="password" autocomplete="${register?'new-password':'current-password'}" required minlength="4"></label><button class="primary">${register?'REGISTRARSE':'INICIAR SESIÓN'}</button></form><button class="link" id="switch">${register?'Ya tengo cuenta: iniciar sesión':'¿No tienes cuenta? Regístrate'}</button><p class="muted">Tus datos permanecen en este dispositivo.</p></main>`;
    document.querySelector('#switch').textContent='Volver al nuevo login';document.querySelector('#switch').onclick=()=>auth();
    document.querySelector('#auth').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('username')).trim().toLowerCase(),pass=String(f.get('password'));if(!/^[\p{L}\p{N}_-]{3,30}$/u.test(name)){legacyAuth(register,'Usa de 3 a 30 letras o números en el usuario.');return}if(register){if(data.users[name]){legacyAuth(true,'Ese usuario ya existe en este teléfono.');return}const salt=random();data.users[name]={salt,passwordHash:await hash(pass,salt),recipes:structuredClone(starters)};data.session=name}else{const u=data.users[name];if(!u || u.passwordHash!==await hash(pass,u.salt)){legacyAuth(false,'Usuario o contraseña incorrectos.');return}data.session=name}save();page='home';render()};
  }
  function cloudLogin(cloudUser) {
    if (!cloudUser?.id) throw Error('No se pudo verificar la identidad.');
    const id = 'cloud:' + cloudUser.id;
    if (!data.users[id]) data.users[id] = {recipes: structuredClone(starters)};
    Object.assign(data.users[id], {email:cloudUser.email, displayName:cloudUser.user_metadata?.username || cloudUser.user_metadata?.full_name || cloudUser.email});
    data.session=id; localStorage.setItem(KEY,JSON.stringify(data)); page='home'; render(); window.RecetarioExtras?.sync();
  }
  function auth() {
    const hasLegacy=Object.values(data.users).some(u=>u?.passwordHash);
    window.RecetarioLogin.mount(app,cloudLogin,()=>legacyAuth(false),hasLegacy);
  }
  function header(){return `<header class="top"><div class="brand">${icon()}<span>Mi Recetario</span></div><p class="muted">¿Qué cocinamos hoy?</p><input id="search" class="search" type="search" placeholder="Buscar recetas" value="${esc(query)}" aria-label="Buscar recetas"></header>`}
  function cards(list){return list.map(r=>`<article class="card"><div class="food" aria-hidden="true">${window.RecetarioExtras.photoMarkup(r)||esc(r.emoji)}</div><div><h2>${esc(r.name)}</h2><p>${esc(r.category)} · ${esc(r.difficulty)}</p><span class="meta">◷ ${esc(r.minutes)} min</span></div><button class="open-card" data-detail="${esc(r.id)}" aria-label="Abrir ${esc(r.name)}"></button><button class="heart" data-fav="${esc(r.id)}" aria-label="${r.favorite?'Quitar de favoritos':'Agregar a favoritos'}">${r.favorite?'♥':'♡'}</button></article>`).join('')}
  function listing(favorites=false){const cats=['Todas','Desayuno','Almuerzo','Cena','Postres','Bebidas'];const filtered=recipes().filter(r=>(!favorites||r.favorite)&&(category==='Todas'||favorites||r.category===category)&&r.name.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));shell(`${header()}<div class="feature-links"><button class="secondary" data-go="catalog">Catálogo</button><button class="secondary" data-go="suggestions">¿Qué puedo cocinar?</button><button class="secondary" data-go="plan">Planificar comida</button></div>${favorites?'':`<div class="chips">${cats.map(c=>`<button data-category="${c}" class="chip ${category===c?'active':''}">${c}</button>`).join('')}</div>`}<section class="content"><div class="heading"><h1>${favorites?'Mis favoritos':'Mis recetas'}</h1><span class="count">${filtered.length} receta${filtered.length===1?'':'s'}</span></div>${filtered.length?cards(filtered):`<div class="empty"><div class="emoji">${favorites?'♡':'🍳'}</div><h2>${favorites?'Todavía no hay favoritos':'No encontramos recetas'}</h2><p>${favorites?'Toca el corazón de una receta para guardarla.':'Prueba otra búsqueda o agrega una receta.'}</p></div>`}</section>${favorites?'':'<button class="add" data-go="form" aria-label="Agregar receta">+</button>'}`);
    document.querySelector('#search').oninput=e=>{query=e.target.value;const pos=e.target.selectionStart;listing(favorites);const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos)};
  }
  function detail(id){const r=recipes().find(x=>x.id===id);if(!r){page='home';return render()}shell(`<button class="back" data-go="home">‹ Volver a recetas</button><div class="detail-hero" aria-hidden="true">${window.RecetarioExtras.photoMarkup(r)||esc(r.emoji)}</div><section class="detail"><h1>${esc(r.name)}</h1><div class="badges"><span class="badge">◷ ${esc(r.minutes)} min</span><span class="badge">${esc(r.servings)} porciones</span><span class="badge">${esc(r.difficulty)}</span><span class="badge">${esc(r.category)}</span></div><h2>Ingredientes</h2><ul>${r.ingredients.map(i=>`<li>${esc(i)}</li>`).join('')}</ul><h2>Preparación</h2><ol>${r.steps.map((s,i)=>`<li>${esc(s)}${window.RecetarioExtras.timerMarkup(r,i)}</li>`).join('')}</ol><button class="secondary" data-needs="${esc(r.id)}">Calcular ingredientes faltantes</button><button class="primary" data-cook="${esc(r.id)}">Confirmar receta preparada</button><button class="secondary" data-fav="${esc(r.id)}">${r.favorite?'♥ Quitar de favoritos':'♡ Agregar a favoritos'}</button><button class="secondary" data-edit="${esc(r.id)}">Editar receta</button><button class="danger" data-delete="${esc(r.id)}">Eliminar receta</button></section>`);window.RecetarioExtras.bindDetail(r)}
  function form(id){const r=recipes().find(x=>x.id===id);shell(`<button class="back" data-go="home">‹ Cancelar</button><form id="recipe-form" class="form"><h1>${r?'Editar receta':'Nueva receta'}</h1>${message?`<p class="error">${esc(message)}</p>`:''}<label class="field">Nombre<input name="name" maxlength="80" required value="${esc(r?.name||'')}"></label><div class="row"><label class="field">Categoría<select name="category">${['Desayuno','Almuerzo','Cena','Postres','Bebidas'].map(c=>`<option ${r?.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label class="field">Dificultad<select name="difficulty">${['Fácil','Media','Difícil'].map(c=>`<option ${r?.difficulty===c?'selected':''}>${c}</option>`).join('')}</select></label></div><div class="row"><label class="field">Minutos<input name="minutes" type="number" min="1" max="1440" required value="${esc(r?.minutes||30)}"></label><label class="field">Porciones<input name="servings" type="number" min="1" max="100" required value="${esc(r?.servings||2)}"></label></div><label class="field">Emoji del plato<input name="emoji" maxlength="8" value="${esc(r?.emoji||'🍲')}"></label><label class="field">Ingredientes (uno por línea)<textarea name="ingredients" required>${esc(r?.ingredients.join('\n')||'')}</textarea></label><label class="field">Pasos (uno por línea)<textarea name="steps" required>${esc(r?.steps.join('\n')||'')}</textarea></label><button class="primary">Guardar receta</button></form>`);
    window.RecetarioExtras.enhanceForm(r);
    document.querySelector('#recipe-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),ingredients=String(f.get('ingredients')).split('\n').map(x=>x.trim()).filter(Boolean),steps=String(f.get('steps')).split('\n').map(x=>x.trim()).filter(Boolean);if(!ingredients.length||!steps.length){message='Agrega al menos un ingrediente y un paso.';form(id);return}const next={id:r?.id||crypto.randomUUID(),name:String(f.get('name')).trim(),category:String(f.get('category')),difficulty:String(f.get('difficulty')),minutes:Number(f.get('minutes')),servings:Number(f.get('servings')),emoji:String(f.get('emoji')).trim()||'🍲',ingredients,steps,favorite:r?.favorite||false};window.RecetarioExtras.collectForm(next);if(r)Object.assign(r,next);else recipes().unshift(next);save();message='';page='detail';editing=next.id;render()};
  }
  function profile(){shell(`<section class="profile"><div class="brand">${icon()} Mi Recetario</div><h1>Mi perfil</h1><div class="panel"><h2>${esc(user().displayName || data.session)}</h2><p>${recipes().length} recetas en tu recetario.</p><p class="notice">Funciona sin Internet después de abrirla una vez en Safari. Consulta el estado de sincronización abajo. Los cambios sin conexión quedan pendientes hasta sincronizar.</p></div><button class="secondary" id="logout">Cerrar sesión</button><button class="secondary" id="export">Exportar mis recetas</button><label class="field">Importar respaldo JSON<input id="import" type="file" accept="application/json,.json"></label></section>`);window.RecetarioExtras.profile();document.querySelector('#logout').onclick=()=>{const cloud=data.session?.startsWith('cloud:');data.session=null;save();render();if(cloud)window.RecetarioLogin.service.logout().catch(()=>{})};document.querySelector('#export').onclick=()=>{const blob=new Blob([JSON.stringify({app:'Mi Recetario',recipes:recipes()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mis-recetas.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};document.querySelector('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(parsed.app!=='Mi Recetario'||!Array.isArray(parsed.recipes))throw Error();const valid=parsed.recipes.every(r=>typeof r.id==='string'&&typeof r.name==='string'&&Array.isArray(r.ingredients)&&Array.isArray(r.steps));if(!valid)throw Error();if(confirm(`¿Importar ${parsed.recipes.length} recetas? Reemplazará las recetas actuales de este usuario.`)){user().recipes=parsed.recipes;save();page='home';render()}}catch{alert('El archivo no es un respaldo válido de Mi Recetario.')}}}
  function render(){if(!user()){auth();return}if(page==='home')listing();else if(page==='favorites')listing(true);else if(page==='profile')profile();else if(page==='detail')detail(editing);else if(page==='form')form(editing);else window.RecetarioExtras.draw(page)}
  app.addEventListener('click',e=>{const t=e.target.closest('[data-go],[data-category],[data-detail],[data-fav],[data-edit],[data-delete]');if(!t)return;if(t.dataset.go){window.RecetarioExtras.clearRequirements();page=t.dataset.go;editing=null;query='';message='';render()}else if(t.dataset.category){category=t.dataset.category;listing()}else if(t.dataset.detail){editing=t.dataset.detail;page='detail';render()}else if(t.dataset.fav){const r=recipes().find(x=>x.id===t.dataset.fav);if(r){r.favorite=!r.favorite;save();render()}}else if(t.dataset.edit){editing=t.dataset.edit;page='form';render()}else if(t.dataset.delete){const r=recipes().find(x=>x.id===t.dataset.delete);if(r&&confirm(`¿Eliminar la receta «${r.name}»?`)){user().recipes=recipes().filter(x=>x.id!==r.id);save();page='home';editing=null;render()}}});
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
  async function boot() {
    const params=new URLSearchParams(location.search);
    if(params.has('code') || params.has('error')) {
      try {
        if(params.has('error')) throw Error('No se completó el acceso con Google. Intenta de nuevo.');
        const d=await window.RecetarioLogin.service.callback();
        if(!d.session?.user) throw Error('No se pudo completar el acceso.');
        history.replaceState(null,'',location.pathname);
        cloudLogin(d.session.user); return;
      } catch(error) {
        history.replaceState(null,'',location.pathname); auth();
        const p=document.querySelector('#auth-feedback');p.hidden=false;p.className='error';p.textContent=error.message;return;
      }
    }
    render();
  }
  window.RecetarioExtras.init({user,recipes,save,esc,shell,render,session:()=>data.session,local:()=>localStorage.setItem(KEY,JSON.stringify(data)),go:(p,id=null)=>{page=p;editing=id;render()}});
  boot();
  if(user())window.RecetarioExtras.sync();
})();
