/* Catálogo local, sugerencias por ingredientes, planes y lista de compras. */
(() => {
 'use strict';
 const C=window.RecetarioCore;
 const item=(name,qty,unit)=>({name,qty,unit});
 const entry=(key,name,emoji,category,minutes,servings,items,steps,times)=>({id:'catalog:'+key,catalogKey:key,name,emoji,category,minutes,servings,difficulty:'Fácil',ingredients:items.map(i=>`${i.qty} ${i.unit} de ${i.name}`),inventoryItems:items,steps,stepSeconds:times,favorite:false});
 const recipes=[
 entry('arroz-blanco','Arroz blanco','🍚','Almuerzo',25,4,[item('Arroz',400,'g'),item('Agua',800,'ml'),item('Aceite',15,'ml'),item('Sal',5,'g')],['Enjuagar el arroz.','Calentar agua, aceite y sal hasta hervir.','Agregar el arroz y cocinar hasta que baje el agua.','Tapar y cocinar a fuego bajo; comprobar que esté tierno.'],[0,0,0,900]),
 entry('habichuelas','Habichuelas guisadas','🫘','Almuerzo',25,4,[item('Habichuelas cocidas',500,'g'),item('Cebolla',1,'unidad'),item('Ajo',2,'unidad'),item('Salsa de tomate',100,'ml'),item('Agua',200,'ml'),item('Aceite',15,'ml'),item('Sal',3,'g')],['Picar la cebolla y el ajo.','Sofreír en aceite y añadir la salsa de tomate.','Agregar las habichuelas cocidas y el agua.','Cocinar a fuego bajo, ajustar la sal y servir.'],[0,180,0,900]),
 entry('pollo-horno','Pollo horneado','🍗','Almuerzo',55,4,[item('Pollo',4,'unidad'),item('Ajo',3,'unidad'),item('Limón',1,'unidad'),item('Aceite',20,'ml'),item('Sal',5,'g')],['Precalentar el horno a 200 °C.','Sazonar el pollo con ajo, limón, aceite y sal.','Colocar en una bandeja y hornear. El tiempo depende del tamaño de las piezas.','Verificar con termómetro que el centro alcance 74 °C; prolongar la cocción si es necesario.'],[0,0,2400,0]),
 entry('huevos','Huevos revueltos','🍳','Desayuno',10,2,[item('Huevos',4,'unidad'),item('Aceite',10,'ml'),item('Sal',2,'g')],['Batir los huevos con la sal.','Calentar el aceite a fuego medio bajo.','Agregar los huevos y remover hasta que estén cuajados.'],[0,0,180]),
 entry('ensalada','Ensalada de tomate','🥗','Cena',10,2,[item('Tomate',2,'unidad'),item('Cebolla',.5,'unidad'),item('Limón',1,'unidad'),item('Aceite',15,'ml'),item('Sal',2,'g')],['Lavar los vegetales.','Cortar tomate y cebolla.','Mezclar con limón, aceite y sal.'],[0,0,0]),
 entry('avena','Avena con leche','🥣','Desayuno',15,2,[item('Avena',80,'g'),item('Leche',400,'ml'),item('Azúcar',15,'g')],['Calentar la leche a fuego bajo.','Agregar avena y azúcar.','Remover hasta que la avena esté cocida y tenga la textura deseada.'],[0,0,480]),
 entry('pasta-tomate','Pasta con tomate','🍝','Cena',25,2,[item('Pasta',200,'g'),item('Salsa de tomate',150,'ml'),item('Ajo',1,'unidad'),item('Aceite',10,'ml'),item('Sal',3,'g'),item('Agua',1500,'ml')],['Hervir agua con sal y cocer la pasta según el paquete.','Sofreír el ajo con aceite y agregar la salsa.','Escurrir la pasta y mezclar con la salsa.'],[600,180,0]),
 entry('tortilla','Tortilla de papas','🥔','Cena',30,2,[item('Papas',2,'unidad'),item('Huevos',3,'unidad'),item('Cebolla',.5,'unidad'),item('Aceite',30,'ml'),item('Sal',3,'g')],['Pelar y cortar las papas y la cebolla.','Cocinar las papas y la cebolla en aceite hasta ablandar.','Batir los huevos con sal y mezclarlos con las papas.','Cocinar la tortilla por ambos lados hasta que el huevo esté cuajado.'],[0,900,0,0])
 ];
 let B,input='',results=null,catalogQuery='',activeSession=null;
 const esc=x=>B.esc(x),id=()=>crypto.randomUUID();
 function state(){const s=B.state();s.shoppingList??=[];s.mealPlan??=[];return s}
 function rows(r){return r.inventoryItems||B.examples[r.id]||[]}
 function scaled(r,portions){return rows(r).map(i=>({...i,qty:C.round(i.qty*portions/(r.servings||1))}))}
 function planItems(){return state().mealPlan.flatMap(p=>{const r=B.recipes().find(r=>r.id===p.recipeId);return r?scaled(r,p.portions):[]})}
 function addPlan(recipeId){const r=B.recipes().find(r=>r.id===recipeId);if(!r)return;const s=state();if(!s.mealPlan.some(p=>p.recipeId===recipeId)){s.mealPlan.push({recipeId,portions:r.servings||1});B.save()}B.go('plan')}
 function recipeCard(r,extra=''){const saved=B.recipes().find(x=>x.catalogKey===r.catalogKey);return `<article class="panel"><h2>${esc(r.emoji)} ${esc(r.name)}</h2><p>${r.minutes} min · ${r.servings} porciones · ${esc(r.category)}</p>${extra}<details><summary>Ingredientes y preparación</summary><ul>${r.ingredients.map(i=>`<li>${esc(i)}</li>`).join('')}</ul><ol>${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></details>${r.catalogKey?`<button class="secondary" data-catalog-save="${esc(r.catalogKey)}">${saved?'Abrir en mi recetario':'Guardar en mi recetario'}</button>`:`<button class="secondary" data-open-own="${esc(r.id)}">Abrir receta</button>`}</article>`}
 function bindCards(){document.querySelectorAll('[data-catalog-save]').forEach(b=>b.onclick=()=>{const key=b.dataset.catalogSave;let r=B.recipes().find(x=>x.catalogKey===key);if(!r){r=structuredClone(recipes.find(x=>x.catalogKey===key));r.id=id();B.recipes().unshift(r);B.save()}B.go('detail',r.id)});document.querySelectorAll('[data-open-own]').forEach(b=>b.onclick=()=>B.go('detail',b.dataset.openOwn))}
 function catalog(){const list=recipes.filter(r=>C.norm(r.name).includes(C.norm(catalogQuery)));B.shell(`<section class="extras"><h1>Catálogo de recetas</h1><p>Ideas para tu cocina. Guarda una copia para editarla y planificar tu comida.</p><form id="catalog-search"><label class="field">Buscar receta<input name="query" value="${esc(catalogQuery)}" placeholder="Arroz, pollo…"></label><button class="secondary">Buscar</button></form>${list.map(r=>recipeCard(r)).join('')||'<p>No encontramos recetas con ese nombre.</p>'}</section>`);document.querySelector('#catalog-search').onsubmit=e=>{e.preventDefault();catalogQuery=new FormData(e.target).get('query');catalog()};bindCards()}
 // Sugerencias deterministas. No genera recetas nuevas ni usa un servicio de IA.
 function ingredientKey(s){let n=C.norm(s);const aliases={'huevo':'huevos','papa':'papas','habichuelas':'habichuelas cocidas','tomates':'tomate'};return aliases[n]||n}
 function ingredientNames(r){return [...new Set((rows(r).length?rows(r).map(i=>i.name):r.ingredients.map(s=>String(s).replace(/^\s*[\d.,/]+\s*(?:kg|g|ml|l|tazas?|cucharadas?|cucharaditas?|unidades?)?\s*(?:de\s+)?/i,''))).map(ingredientKey))]}
 function recommend(names){const available=new Set(names.map(ingredientKey));const own=B.recipes(),all=[...own,...recipes.filter(r=>!own.some(o=>o.catalogKey===r.catalogKey))];return all.map(r=>{const names=ingredientNames(r),missing=names.filter(n=>!available.has(n)),matched=names.length-missing.length;return {r,missing,matched,ratio:names.length?matched/names.length:0}}).filter(x=>x.matched>0).sort((a,b)=>a.missing.length-b.missing.length||b.ratio-a.ratio||b.matched-a.matched)}
 function suggestions(){B.shell(`<section class="extras"><h1>¿Qué puedo cocinar?</h1><p>Busca coincidencias en tu recetario y en el catálogo.</p><form id="suggest-form"><label class="field">Ingredientes disponibles<textarea name="ingredients" placeholder="Arroz, huevos, pollo">${esc(input)}</textarea></label><p>Separa los nombres con comas o líneas. Incluye también agua, aceite y sal si los tienes.</p><button class="primary">Buscar recetas</button><button class="secondary" type="button" id="use-pantry">Usar ingredientes del inventario</button></form>${results===null?'':`<h2>${results.length} sugerencias</h2><p class="notice">La búsqueda compara nombres. Revisa las cantidades, los ingredientes y las porciones antes de cocinar.</p>${results.map(({r,missing,matched})=>recipeCard(r,`<p><strong>${missing.length?'Faltan '+missing.length+' ingredientes':'Coinciden todos los ingredientes'}</strong></p><p>${matched} coincidencias${missing.length?' · Faltan: '+esc(missing.join(', ')):''}</p>`)).join('')||'<p>No encontramos coincidencias. Prueba con otros ingredientes.</p>'}`}</section>`);document.querySelector('#suggest-form').onsubmit=e=>{e.preventDefault();input=String(new FormData(e.target).get('ingredients'));results=recommend(input.split(/[,\n]/).map(s=>s.trim()).filter(Boolean));suggestions()};document.querySelector('#use-pantry').onclick=()=>{input=state().inventory.filter(i=>i.qty>0).map(i=>i.name).join(', ');results=recommend(input.split(',').map(s=>s.trim()).filter(Boolean));suggestions()};bindCards()}
 function plan(){const s=state();s.mealPlan=s.mealPlan.filter(p=>B.recipes().some(r=>r.id===p.recipeId));B.shell(`<section class="extras"><h1>Planificar comida</h1><p>Combina tus recetas y ajusta las porciones de cada plato.</p><button class="secondary" data-go="home">Seleccionar más recetas</button>${s.mealPlan.map(p=>{const r=B.recipes().find(r=>r.id===p.recipeId);return `<article class="panel"><h2>${esc(r.emoji)} ${esc(r.name)}</h2><label class="field">Porciones<input data-portions="${esc(r.id)}" type="number" min="1" max="100" step="1" value="${p.portions}"></label><p>${rows(r).length?'Ingredientes ajustados a estas porciones':'Sin cantidades: edita esta receta para incluirla en el cálculo'}</p><button class="secondary" data-plan-edit="${esc(r.id)}">Editar receta</button><button class="secondary" data-plan-open="${esc(r.id)}">Ver pasos y temporizadores</button><button class="danger" data-plan-remove="${esc(r.id)}">Quitar del plan</button></article>`}).join('')||'<p>No has seleccionado recetas. Abre una receta y pulsa “Agregar al plan de comida”.</p>'}${s.mealPlan.length?'<button class="primary" id="plan-needs">Calcular faltantes de toda la comida</button><button class="secondary" id="plan-list">Agregar faltantes a mi lista de compras</button><button class="secondary" id="plan-cook">Confirmar comida preparada</button><button class="danger" id="plan-clear">Cancelar plan</button>':''}</section>`);
 document.querySelectorAll('[data-portions]').forEach(b=>b.onchange=()=>{const n=Number(b.value);if(!Number.isInteger(n)||n<1||n>100){plan();return}s.mealPlan.find(p=>p.recipeId===b.dataset.portions).portions=n;B.save();plan()});
 document.querySelectorAll('[data-plan-remove]').forEach(b=>b.onclick=()=>{s.mealPlan=s.mealPlan.filter(p=>p.recipeId!==b.dataset.planRemove);B.save();plan()});
 document.querySelectorAll('[data-plan-edit]').forEach(b=>b.onclick=()=>B.go('form',b.dataset.planEdit));
 document.querySelectorAll('[data-plan-open]').forEach(b=>b.onclick=()=>B.go('detail',b.dataset.planOpen));
 const ready=()=>{if(s.mealPlan.some(p=>!rows(B.recipes().find(r=>r.id===p.recipeId)).length)){alert('Registra las cantidades de todas las recetas antes de calcular la comida.');return false}return true};
 document.querySelector('#plan-needs')?.addEventListener('click',()=>{if(ready())B.showNeeds(C.needs(planItems(),s.inventory).filter(i=>i.missing>0))});
 document.querySelector('#plan-list')?.addEventListener('click',()=>{if(ready()){addMissing(C.needs(planItems(),s.inventory).filter(i=>i.missing>0));B.go('shopping-list')}});
 document.querySelector('#plan-clear')?.addEventListener('click',()=>{if(confirm('¿Quitar todas las recetas del plan?')){s.mealPlan=[];B.save();plan()}});
 document.querySelector('#plan-cook')?.addEventListener('click',()=>{if(!ready())return;const items=planItems(),missing=C.needs(items,s.inventory).filter(i=>i.missing>0);if(missing.length)return alert('Faltan: '+missing.map(i=>i.name+' ('+i.missing+' '+i.unit+')').join(', '));if(!confirm('¿Confirmar que preparaste todas las recetas del plan? Se descontarán las cantidades ajustadas y se vaciará el plan.'))return;s.inventory=C.consume(s.inventory,items);s.cooked.push({id:id(),recipe:s.mealPlan.map(p=>B.recipes().find(r=>r.id===p.recipeId).name).join(' + '),date:new Date().toISOString(),items:structuredClone(items)});s.mealPlan=[];B.save();plan();alert('Comida registrada e inventario actualizado.')});
 }
 function addMissing(items){const s=state();items.forEach(i=>{const existing=s.shoppingList.find(x=>!x.bought&&C.norm(x.name)===C.norm(i.name)&&C.convert(i.missing,i.unit,x.unit)!==null);if(existing)existing.qty=C.round(Math.max(existing.qty,C.convert(i.missing,i.unit,existing.unit)));else s.shoppingList.push({id:id(),name:i.name,qty:i.missing,unit:i.unit,bought:false})});B.save()}
 function shoppingList(editId){const s=state(),editing=s.shoppingList.find(i=>i.id===editId),pending=s.shoppingList.filter(i=>!i.bought),bought=s.shoppingList.filter(i=>i.bought);const line=i=>`<article class="stock-line"><div><label><input class="shopping-check" data-check-list="${i.id}" type="checkbox" ${i.bought?'checked':''}> <strong>${esc(i.name)}</strong></label><p>${i.qty} ${esc(i.unit)}</p></div><button class="secondary compact" data-list-edit="${i.id}">Editar</button><button class="danger compact" data-list-delete="${i.id}">Quitar</button></article>`;
 B.shell(`<section class="extras"><h1>Lista para el supermercado</h1><p>Marca lo comprado y confirma las cantidades que trajiste a casa.</p><form id="list-form" class="panel"><h2>${editing?'Editar producto':'Agregar producto'}</h2><label class="field">Producto<input name="name" required maxlength="80" value="${esc(editing?.name||'')}"></label><div class="row"><label class="field">Cantidad<input name="qty" type="number" min="0.000001" step="any" required value="${editing?.qty??''}"></label><label class="field">Unidad<select name="unit">${Object.keys(C.units).map(unit=>`<option ${unit===(editing?.unit||'unidad')?'selected':''}>${unit}</option>`).join('')}</select></label></div><button class="primary">Guardar producto</button></form><h2>Pendientes (${pending.length})</h2>${pending.map(line).join('')||'<p>No hay pendientes.</p>'}<h2>Comprados (${bought.length})</h2>${bought.map(line).join('')||'<p>Aún no has marcado productos.</p>'}${bought.length?'<button class="primary" id="receive-list">Confirmar llegada a casa</button><p>Antes de confirmar, edita las cantidades si compraste más o menos. Los productos confirmados se suman al inventario y salen de esta lista.</p>':''}</section>`);
 document.querySelector('#list-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),next={name:String(f.get('name')).trim(),qty:Number(f.get('qty')),unit:String(f.get('unit'))};if(!next.name||!Number.isFinite(next.qty)||next.qty<=0)return;if(editing)Object.assign(editing,next);else s.shoppingList.push({...next,id:id(),bought:false});B.save();shoppingList()};
 document.querySelectorAll('[data-check-list]').forEach(b=>b.onchange=()=>{s.shoppingList.find(i=>i.id===b.dataset.checkList).bought=b.checked;B.save();shoppingList()});
 document.querySelectorAll('[data-list-edit]').forEach(b=>b.onclick=()=>{shoppingList(b.dataset.listEdit);document.querySelector('#list-form').scrollIntoView({behavior:'smooth',block:'start'})});
 document.querySelectorAll('[data-list-delete]').forEach(b=>b.onclick=()=>{s.shoppingList=s.shoppingList.filter(i=>i.id!==b.dataset.listDelete);B.save();shoppingList()});
 document.querySelector('#receive-list')?.addEventListener('click',()=>{const items=s.shoppingList.filter(i=>i.bought);if(!items.length||!confirm('¿Sumar al inventario los productos marcados y retirarlos de la lista?'))return;items.forEach(i=>C.addStock(s.inventory,{...i,id:id()}));s.orders.push({id:id(),date:new Date().toISOString(),items:items.map(i=>({...i,packs:1,price:0})),total:0,method:'Compra externa · importe no registrado',received:true,receivedAt:new Date().toISOString()});s.shoppingList=s.shoppingList.filter(i=>!i.bought);B.save();shoppingList()});
 }
 window.RecetarioKitchen={init(b){B=b},addPlan,addMissing,draw(page){if(activeSession!==B.session()){activeSession=B.session();input='';results=null;catalogQuery=''}if(page==='catalog')catalog();if(page==='suggestions')suggestions();if(page==='plan')plan();if(page==='shopping-list')shoppingList()}};
})();
